app/core/forms.py
from flask_wtf import FlaskForm
from wtforms import Form,IntegerField, StringField, TextAreaField, BooleanField, PasswordField, FloatField, SelectField
from wtforms.validators import InputRequired, Length, NumberRange, ValidationError
from wtforms.fields.html5 import DateField, DateTimeField

class OrderForm(FlaskForm):
    ord_num = StringField('ord_num', validators=[InputRequired()])
#    create_date = DateTimeField('create_date', validators=[InputRequired()])
#    complete_date = DateTimeField('complete_date', validators=[InputRequired()], format='%Y-%m-%d mm:ss')
    client = StringField('client', validators=[InputRequired()])
    phone = StringField('phone', validators=[InputRequired()])
    discount = IntegerField('discount', render_kw={'placeholder': u'Скидка, до 100%'},default=0)
    discount_sum = IntegerField('discount_sum',default=0,render_kw={'placeholder': u'Скидка, от 0 руб.'})
#    discount = IntegerField('discount',default=0,validators=[InputRequired(), NumberRange(min=0,max=100, message=' Ошибка: скидка от 0 до 100%')])
#    discount_sum = IntegerField('discount_sum',default=0,validators=[InputRequired(), NumberRange(min=0, message=' Ошибка: скидка от 0 руб.')])
#    orders_type_id = IntegerField('orders_type_id')
#    status_id = IntegerField('status_id')
    descr = TextAreaField('descr')
#    status_ord_id = IntegerField('status_ord_id')
#    pay = FloatField('pay', validators=[InputRequired()])
#    pay_date = DateTimeField('pay_date', validators=[InputRequired()])
#    prepayment = FloatField('prepayment', validators=[InputRequired()])
#    prepayment_date = DateTimeField('prepayment_date', validators=[InputRequired()])
#    descr_pay = TextAreaField('descr_pay', validators=[InputRequired()])

    def validate_discount(FlaskForm, field):
        if type(field.data).__name__ != 'int':
            raise ValidationError('Ошибка: введите число от 0 до 100')
        else:
            if int(field.data) < 0 or int(field.data) > 100:
                raise ValidationError('Ошибка: скидка от 0 до 100%')

class OrderTypeForm(FlaskForm):
    class Meta:
        csrf_field_name = 'csrf_token_ordertype'

    name = StringField('name', validators=[InputRequired()])
#    units = StringField('units', validators=[InputRequired()])
    units = SelectField(u'units', choices=[('шт.', 'шт.'),('ед.','ед.'), ('м', 'м'), ('м2', 'м2.'),('мл.','мл.'),('услуга','услуга'),])
    quantity = FloatField('quantity', validators=[InputRequired(), NumberRange(min=1,max=100000000, message='Ошибка ввода: кол-во от 1 ед./шт.')])
    quantity_sum = FloatField('quantity_sum', validators=[InputRequired(), NumberRange(min=0,max=100000000, message='Ошибка ввода: сумма от 0 руб')])


class PayForm(FlaskForm):
    units = SelectField(u'units', choices=[('Наличный','Наличный'),('Безнал.','Безналичный'),])
    pay = FloatField('pay', validators=[InputRequired(), NumberRange(min=0, message='Ошибка: Hекоректный ввод данных')], render_kw={'placeholder': 'Сумма платежа'})
    pay_descr = TextAreaField('pay_descr')

#class CalendarForm(FlaskForm):
#    data_with = StringField('data_with')
#    data_from = StringField('data_from')

class DiscountForm(FlaskForm):
    class Meta:
        csrf_field_name = 'csrf_token_discount'

    discount = IntegerField('discount', render_kw={'placeholder': u'Скидка, до 100%'})
    discount_sum = IntegerField('discount_sum',render_kw={'placeholder': u'Скидка, от 0 руб.'})

    def validate_discount(FlaskForm, field):
        if type(field.data).__name__ != 'int':
            raise ValidationError('Ошибка: введите число от 0 до 100')
        else:
            if int(field.data) < 0 or int(field.data) > 100:
                raise ValidationError('Ошибка: скидка от 0 до 100%')

class EditOrderForm(FlaskForm):
    ord_num = StringField('ord_num', validators=[InputRequired()])
#    create_date = DateTimeField('create_date', validators=[InputRequired()])
#    complete_date = DateTimeField('complete_date', validators=[InputRequired()], format='%Y-%m-%d mm:ss')
    client = StringField('client', validators=[InputRequired()])
    phone = StringField('phone', validators=[InputRequired()])
    discount = IntegerField('discount', render_kw={'placeholder': u'Скидка, до 100%'})
    discount_sum = IntegerField('discount_sum',render_kw={'placeholder': u'Скидка, от 0 руб.'})
#    discount = IntegerField('discount',default=0,validators=[InputRequired(), NumberRange(min=0,max=100, message=' Ошибка: скидка от 0 до 100%')])
#    discount_sum = IntegerField('discount_sum',default=0,validators=[InputRequired(), NumberRange(min=0, message=' Ошибка: скидка от 0 руб.')])
#    orders_type_id = IntegerField('orders_type_id')
#    status_id = IntegerField('status_id')
    descr = TextAreaField('descr')
#    status_ord_id = IntegerField('status_ord_id')
#    pay = FloatField('pay', validators=[InputRequired()])
#    pay_date = DateTimeField('pay_date', validators=[InputRequired()])
#    prepayment = FloatField('prepayment', validators=[InputRequired()])
#    prepayment_date = DateTimeField('prepayment_date', validators=[InputRequired()])
#    descr_pay = TextAreaField('descr_pay', validators=[InputRequired()])

    def validate_discount(FlaskForm, field):
        if type(field.data).__name__ != 'int':
            raise ValidationError('Ошибка: введите число от 0 до 100')
        else:
            if int(field.data) < 0 or int(field.data) > 100:
                raise ValidationError('Ошибка: скидка от 0 до 100%')

class ExpenseCompanyForm(FlaskForm):
    """Форма расходов компании""" 
    name = StringField('name', validators=[InputRequired()])
    quantity_sum = FloatField('quantity_sum', validators=[InputRequired(), NumberRange(min=0,max=999999999, message='Ошибка ввода: сумма от 0 руб')])
    descr = TextAreaField('descr')

class StoreIncomingForm(FlaskForm):
    """ Склад """
    id = IntegerField('id',validators=[InputRequired()])
    vendor = IntegerField('discount',default=0,validators=[InputRequired(), NumberRange(min=1, message='Ошибка: только целые числа в артикуле')])
    name = StringField('name', validators=[InputRequired()])
    units = SelectField(u'units', choices=[('шт.', 'шт.'),('ед.','ед.'), ('м', 'м'), ('м2', 'м2.'),('мл.','мл.'),('услуга','услуга'),])
    quantity = FloatField('quantity', validators=[InputRequired(), NumberRange(min=1,max=100000000, message='Ошибка ввода: кол-во от 1 ед./шт.')])
    quantity_sum = FloatField('quantity_sum', validators=[InputRequired(), NumberRange(min=0,max=100000000, message='Ошибка ввода: сумма от 0 руб')])
    descr = TextAreaField('descr')

class GroupProductForm(FlaskForm):
    """ Группы """
    name = StringField('name', validators=[InputRequired()])
    descr = TextAreaField('descr')


#class ClientForm(FlaskForm):
#    uid = IntegerField('uid')
#    login = StringField('login', validators=[InputRequired('A login is required'), Length(min=3, max=12, message='от 3 до 12 символов')])
#    password = PasswordField('password', validators=[InputRequired()])
#    activate = DateTimeField('activate', validators=[InputRequired()])
#    expire = DateTimeField('expire')
#    status = IntegerField('status')
#    disable = BooleanField('disable')
#    contract_id = StringField('contract_id')
#    contract_date = DateTimeField('contract_date')
#    company_id = IntegerField('company')
#    delete = BooleanField('delete')
#    descr = TextAreaField('descr')

app/core/blueprint.py
from flask import Blueprint
from flask import render_template, request, redirect,session, url_for
from flask_wtf import FlaskForm
#import datetime
from datetime import datetime, date, timedelta
from time import strptime
import sys
from modules.mod_date import ModDatetime
from .forms import OrderForm, OrderTypeForm, PayForm, DiscountForm, EditOrderForm, ExpenseCompanyForm, StoreIncomingForm, GroupProductForm

sys.path.insert(0, '/app/core')
sys.path.insert(0,'/app/modules/orders')
sys.path.insert(0,'/app/modules/pays')
sys.path.insert(0,'/app/modules/expense')
sys.path.insert(0,'/app/modules/store')
core = Blueprint('core',__name__, template_folder='templates')

from mod_store import ModStore
from mod_groupstore import ModGroupStore
from orders import allOrders, infoOrder, addOrder, addOrderType, viewOrder, viewOrderType, selectOrderType, discountOrder, editQuantity, deleteQuantity, editDiscountOrder
from pays import addpay_order, calcPayOrder, selectPaysOrder, calcPaysOrder, calcPayment, allPays, allDatePays, viewPay, deletePay
from expense import allExpense, addExpense, allExpenseCompany, addExpenseCompany, viewExpenseCompanyId, editExpenseCompanyId, deleteExpenseCompanyId
#from store import allStore, allStoreIncoming, addStoreIncoming, listStoreIncomingGID, viewStoreIncomingId, editStoreIncomingId, deleteStoreIncomingId, checkVendorStore

@core.route('/', methods=['GET'])
def index():
    ''' Стартовая страница '''
#    search = request.args.get('search')
#    if search:
#        search = searchClients(search)
#        return render_template('/user/all.html',allClients=search)
#    else:
#        return redirect('/core/users/all')
    return render_template('index.html')

# --- ORDERS ---

@core.route('/orders/all', methods=['GET'])
def orders():
    ''' Список заказов '''
    orders = allOrders()
    return render_template('orders/all.html', allOrders=orders)

@core.route('/orders/create', methods=['POST','GET'])
def create():
    ''' Добавить ордер '''
    form_order = OrderForm()
    info = request.form.to_dict()
    if form_order.validate_on_submit():
        add = []
        for i in form_order:
            if i.data != None:
                add.append((i.name,i.data))
        add_order = dict(add)
        add = addOrder(**add_order)
        if add == 'error':
            error = 'Ошибка договор с номером '+ add_order['ord_num']+' существует'
            return render_template('orders/create.html',form_order=form_order, error=error)
        else:
            return redirect('core/orders/addtype/'+ str(add.id))
    return render_template('orders/create.html',form_order=form_order)

@core.route('/orders/addtype/<order_id>', methods=['POST','GET'])
def addtype(order_id):
    ''' Добавить наименование '''
    view_order = viewOrder(order_id)
    discount_sum = view_order.discount_sum
    form_ordertype = OrderTypeForm()
    form_discount = DiscountForm()
    if request.method == 'POST':
        if form_discount.data['csrf_token_discount'] == '':
            form_discount.data['errors'] = ''
        else:
            if form_discount.validate_on_submit():
                add = []
                for i in form_discount:
                    add.append((i.name, i.data))
                update = dict(add)
                update['csrf_token'] = update.pop('csrf_token_discount')
                edit_discount = editDiscountOrder(order_id,**update)
                if edit_discount == 'Done':
                    return redirect('core/orders/addtype/'+ str(order_id))

        if form_ordertype.data['csrf_token_ordertype'] == '':
            form_ordertype.data['errors'] = ''
        else:
            if form_ordertype.validate_on_submit():
                add = []
                for i in form_ordertype:
                    if i.data != None:
                        add.append((i.name, i.data))
                add_order_type= dict(add)
                add_order_type['oid'] = int(order_id)
                add_order_type = addOrderType(**add_order_type)
                return redirect('core/orders/addtype/'+ order_id)
    sot = selectOrderType(order_id) # Выборка наименований заказа
    orders_sum = sot[1]
    discount = discountOrder(orders_sum,view_order.discount, discount_sum) # Расчет скидки

    pays = calcPayOrder(sot,discount) # Расчет суммы оплат
    selectPays = calcPaysOrder(order_id)
    if selectPays:
        pays_sum_order = selectPays[1]
    else:
        pays_sum_order = 0
    calcOrderSum = calcPayment(orders_sum,discount,pays_sum_order)
    return render_template('orders/addtype.html',view_order=view_order, form_ordertype=form_ordertype, sot=sot,discount=discount,pays=pays, selectPays=selectPays, calcOrderSum=calcOrderSum, form_discount=form_discount)

@core.route('/orders/editorder/<order_id>', methods=['GET','POST'])
def editorder(order_id):
    """Редактирование заказчика"""
    order = viewOrder(order_id)
    form_order = EditOrderForm()
    upd = []
    if request.method == 'POST':
        if form_order.validate_on_submit():
            for i in form_order:
                upd.append((i.name, i.data))
        update = dict(upd)
        upd_order = editDiscountOrder(order_id,**update)
        if upd_order == 'Done':
            return redirect('core/orders/addtype/'+str(order_id))
        else:
            return redirect('core/orders/all')
    return render_template('orders/editorder.html',form_order=form_order, order=order)

@core.route('/orders/edittype/<quantity_id>', methods=['GET','POST'])
def edittype(quantity_id):
    """Редактирование наименование"""
    form_ordertype = OrderTypeForm()
    ordertype = viewOrderType(quantity_id)
    add = []
    if request.method == 'POST':
        if form_ordertype.validate_on_submit():
            for i in form_ordertype:
                add.append((i.name, i.data))
        update = dict(add)
        edit_quantity = editQuantity(quantity_id,**update)
        if edit_quantity == 'Done':
            return redirect('core/orders/addtype/'+ str(ordertype.oid))
        else:
            return redirect('core/orders/all')
    return render_template('orders/edittype.html',form_ordertype=form_ordertype, ordertype=ordertype)


@core.route('/orders/deltype/<quantity_id>', methods=['GET','POST'])
def deltype(quantity_id):
    """Удаление наименования"""
    form_ordertype = OrderTypeForm()
    ordertype = viewOrderType(quantity_id)
    if request.method == 'POST':
        delete_quantity = deleteQuantity(quantity_id)
        if delete_quantity == 'None':
            return redirect('/')
        return redirect('core/orders/addtype/'+ str(delete_quantity))
    return render_template('orders/deletetype.html', form_ordertype=form_ordertype, ordertype=ordertype)

# --- PAYS ---

@core.route('/pays/allpays', methods=['GET','POST'])
def allpays():
    """Оплаты"""
    data = allPays()
    day = {}
    day['dmyw'] = date.today().strftime('01-%m-%Y')
    day['dmyf'] = date.today().strftime('%d-%m-%Y')

    if request.method == 'POST':
        moddatetime= ModDatetime()
        date_with = moddatetime.reverse_date(request.form['date_with'])
        date_from = moddatetime.reverse_date(request.form['date_from'])
        data = allDatePays(date_with,date_from)
        day['dmyw']=request.form['date_with']
        day['dmyf']=request.form['date_from']
#        day['mm'] = last_day_of_month(date.today())
        dataYear = ''
        return render_template('pays/allpays.html', allpays=data, day=day, dataYear=dataYear)
    return render_template('pays/allpays.html', allpays=data, day=day)


@core.route('/pays/add/<order_id>', methods=['GET','POST'])
def pay_order(order_id):
    """Добавление платежа"""
    form_pay = PayForm(request.form)
    if request.method == 'POST' and form_pay.validate():
        add = []
        for i in form_pay:
            if i.data != None:
                add.append((i.name,i.data))
        pay = dict(add)
        add = addpay_order(order_id,**pay)
        return redirect('core/orders/addtype/'+str(order_id))
    return render_template('pays/addpay.html', form_pay=form_pay)

@core.route('/pays/del/<id>', methods=['GET','POST'])
def deletepay(id):
    """ Удаление оплаты по ID """
    form_pay = PayForm(request.form)
    data = viewPay(id)
    if request.method == 'POST':
        if data is not None:
            delete = deletePay(id)
            return redirect('core/orders/addtype/'+str(data.oid))
        else:
            return redirect('core/orders/all')
    return render_template('pays/delete_pay.html', form_pay=form_pay, data=data)

# --- EXPENSE ---

@core.route('/expense/allexpenses', methods=['GET','POST'])
def allexpenses():
    """Расходы"""
    allexpense = allExpense()
    return render_template('expenses/allexpense.html', data = allexpense)

@core.route('/expense/addexpense', methods=['POST'])
def addexpense():
    """Добавить позицию расходов"""
    if  request.method == 'POST':
        form = request.form.to_dict()
        print('---form-expense---'*9)
        print(form)
        add = addExpense(order_id,**form)
        return render_template('expenses/allexpense.html')
    return render_template('expenses/addexpense.html')

@core.route('/expense/company/all')
def allcompanyexpense():
    """Список всех расходов для фирмы"""
    data = allExpenseCompany()
    return render_template('expenses/company/all.html',data=data)

@core.route('/expense/company/add', methods=['GET','POST'])
def addcompanyexpense():
    """Создание позиции расходов для фирмы"""
    form = ExpenseCompanyForm(request.form)
    if request.method == 'POST' and form.validate():
        add = []
        for i in form:
            if i.data != None:
                add.append((i.name,i.data))
        add_data = dict(add)
        del add_data['csrf_token']
        add = addExpenseCompany(**add_data)
        if add == 'error':
            error = 'Ошибка'
            return render_template('expense/company/add.html',form=form, error=error)
        else:

app/core/templates/orders/addtype.html
{% extends 'base.html' %} 

{% block title %}
	Редактирование заказа
{% endblock %}

{% block content_titel %}
	Редактирование заказа
{% endblock %}

{% block content %}
{% from "_formhelpers.html" import render_field %}
<div class="grid-x grid-padding-x">
  <div class="medium-12 cell">
    <div class="grid-x grid-padding-x">
      <div class="medium-6 cell">
        <div class="medium-12">
          <div class="grid-x grid-padding-x">
            <div class="medium-6 medium-offset-1">
              Заказ: № {{ view_order.ord_num }}
            </div>
            <div class="medium-4">
              {{ view_order.create_date.strftime('%Y-%m-%d %H:%M:%S') }}
            </div>
            <div class="small-12 medium-12 callout secondary">
              <div class="grid-x grid-padding-x">
                <div class="small-12 medium-6 medium-offset-1 callout secondary">
                  <label>Заказчик:
                    {{ view_order.client }}
                  </label>
                  <label>Телефон:
                    {{ view_order.phone}}
                  </label>
                <a class="button success small" href="/core/orders/editorder/{{ view_order.id  }}">Редактирование</a>
                </div>
                <div class="small-12 medium-6 medium-offset-1 callout secondary">
                  <div>
                  <label>
                  Скидка,% : {{ view_order.discount }}
                  </label>
                  <label>
                  Скидка,руб :  {{ view_order.discount_sum }}
                  </label>
                  </div>
                </div>
              </div>
                <b>Оплаты:</b>
                <table class="stack">
                  <thead>
                    <tr>
                      <th width="7%">ID</th>
                      <th width="14%">Вид платежа</th>
                      <th width="22%">Дата</th>
                      <th width="15%">Сумма платежа</th>
                      <th width="28%">Описание</th>
                      <th width="5%"></th>
                    </tr>
                  </thead>
                  {% for pay in selectPays[0] %}
                  <tbody>
                    <tr>
                      <td>{{ pay.id }}</td>
                      <td>{{ pay.units }}</td>
                      <td>{{ pay.pay_date.strftime('%Y-%m-%d %H:%M:%S') }}</td>
                      <td>{{ pay.pay }} руб.</td>
                      <td>{{ pay.pay_descr }}</td>
                      <td><a href="{{ get_ablolute_url  }}/core/pays/del/{{ pay.id }}">уд.</td>
                    </tr>
                  </tbody>
                {% endfor %}
                </table>
            </div>
          </div>
        </div>
      </div>
      <div class="medium-6 cell callout secondary">
          <div class="grid-x grid-padding-x">
            <div class="medium-12 medium-offset-1 callout secondary">
              <b>Счет фактура:</b> | 
              Выполнение: {{ view_order.complete}}  |
              {{ view_order.status_id}}
          <div class="grid-x grid-padding-x">
            <div class="small-12 medium-6 medium-offset-1 callout secondary">
              <div>
              </div>
            </div>
            <div class="small-12 medium-6 medium-offset-1 callout secondary">
              <div>
                <b>Сумма заказа: </b> {{ sot[1]|round(2) }} руб.
              </div>
                {% if selectPays %}
              <div>
                <b>Скидка:</b> {{ discount|round(2) }} руб.
              </div>
              <div>
                  <b>К оплате:</b> {{ pays|round(2) }} руб.
              </div>  
                {% endif %}  
              <hr>
              <div>
                {% if selectPays %}
                <b>Предоплата:</b>
                  {{ selectPays[1]|round(2)}} руб.
                {% endif %}
                <form method="POST">
                  <a class="button success small" href="/core/pays/add/{{ view_order.id }}">Внести оплату</a>
                </form>
              </div>
              <hr>
              <div>
                {% if calcOrderSum %}
                {% if selectPays %}
                <b>Оплачено:</b>
                  {{ selectPays[1] |round(2) }} руб.
                {% endif %}
                <b>Остаток:</b> {{ calcOrderSum.remainder |round(2)}}  руб.
              </div>
              <div>
                {% if selectPays[1] %}
                  <b>Итог:</b> {{ selectPays[1]|round(2) }} руб. | Статус заказа
                {% endif %}
              </div>
              <div>
                <b> Сдача:</b> {{ calcOrderSum.surrender |round(2)}}  руб.
              </div>
                {% endif %}
            </div>
          </div>
      </div>
    </div>
  </div>
</div>
<div class="medium-12 cell">
  <div class="grid-x grid-padding-x">
    <div class="medium-12 cell">
    <form method="POST">
      {{ form_ordertype.csrf_token_ordertype  }}
      <div class="grid-x grid-margin-x">
        <div class="medium-5  medium-offset-7">
              {% for error in form_ordertype.quantity.errors %}
                <li style="color:red;">{{ error }}</li>
              {% endfor %}
              {% for error in form_ordertype.quantity_sum.errors %}
                <li style="color:red;">{{ error }}</li>
              {% endfor %}
        </div>
              <div class="cell small-12 medium-6 large-6">
                  {{form_ordertype.name(placeholder="Вид заказа")}}
              </div>
              <div class="cell small-12 medium-1 large-1">
                  {{form_ordertype.quantity(placeholder="Кол-во")}}
              </div>
              <div class="cell small-12 medium-1 large-1">
                  {{form_ordertype.units(placeholder="Ед.")}}
              </div>
              <div class="cell small-12 medium-1 large-1">
                  {{form_ordertype.quantity_sum(placeholder="Цена")}} 
              </div>
              <div>
                  <input type="submit" class="button" value="Submit">
              </div>
          </div>
      </div>
    </form>
  </div>
</div>
<hr>
<div class="medium-12 cell">
  <div class="grid-x grid-padding-x">
    <div class="medium-6 cell">
      Продажа
      <table class="stack">
        <thead>
          <tr>
            <th width="50%">Наименнование заказа</th>
            <th width="16%">Кол-во</th>
            <th width="7%">Ценa, руб</th>
            <th width="7%">Сумма, руб</th>
            <th width="15%"></th>
          </tr>
        </thead>
        {% for order in sot[0] %}
        <tbody>
          <tr>
            <td>{{ order[0].name }}</td>
            <td>{{ order[0].quantity}} | {{ order[0].units }}</td>
            <td>{{ order[0].quantity_sum|round(2)}}</td>
            <td>{{ order[1]|round(2)}}</td>
            <td><a href="{{ get_ablolute_url  }}/core/orders/edittype/{{ order[0].id }}">ред. </a> / <a href="{{ get_ablolute_url  }}/core/orders/deltype/{{ order[0].id }}">уд.</a></td>
          </tr>
        </tbody>
      {% endfor %}
      </table>
    </div>
    <div class="medium-6 cell">
      Затраты <a href="{{ get_ablolute_url }}/core/store/addexpense/{{ view_order.id }}">Добавить затраты</a>
      <table class="stack">
        <thead>
          <tr>
            <th>Артикул</th>
            <th width="50%">Наименнование</th>
            <th width="16%">Кол-во</th>
            <th width="7%">Ценa, руб</th>
            <th width="7%">Сумма, руб</th>
            <th width="15%"></th>
          </tr>
        </thead>
        {% for order in sot[0] %}
        <tbody>
          <tr>
            <td>###</td>
            <td>{{ order[0].name }}</td>
            <td>{{ order[0].quantity}} | {{ order[0].units }}</td>
            <td>{{ order[0].quantity_sum|round(2)}}</td>
            <td>{{ order[1]|round(2)}}</td>
            <td></td>
          </tr>
        </tbody>
      {% endfor %}
      </table>
    </div>
  </div>
</div>
            <div class="small-12 medium-12 callout secondary">
              <label>Заметки:
              </label>
                <div class=row>
                  <div class="callout text-left">
                    <p class="text-left leag" >{{ view_order.descr}}<p>
                  </div>
                </div>
            </div>
{% endblock %}

app/core/templates/orders/all.html
{% extends 'base.html' %}
{% block title %} Информация о заказах {% endblock %}

{% block content_title %}  <h5>Информация о заказах</h5> {% endblock %}

{% block content %}
<div class="medium-12 cell large-offset-1">
  <div class="grid-x grid-padding-x">
    <div class="medium-10 cell">
      <p>{{ allOrders.search }}</p>
      <table class="stack">
        <thead>
          <tr>
            <th width="25">№ заказа</th>
            <th width="350">Заказчик</th>
            <th width="200">Телефон</th>
            <th width="200">Cтатус заказа</th>
            <th width="300">Дата создания</th>
          </tr>
        </thead>
        {% for order in allOrders %}
        <tbody>
          <tr>
            <td><a href="{{ get_absolute_url  }}/core/orders/addtype/{{ order.id }}">{{ order.ord_num }}</td>
            <td>{{ order.client }}</td>
            <td>{{ order.phone }}</td>
            <td>Выполнено</td>
            <td>{{ order.create_date.strftime('%Y-%m-%d %H:%m:%S')}}</td>
	    

          </tr>
        </tbody>
      {% endfor %}
      </table>
    </div>
  </div>
</div>
{% endblock %}

app/core/templates/orders/create.html
{% extends 'base.html' %}

{% block title %}
Создание заказа
{% endblock %}

{% block content_titel %}
  Создать заказ
{% endblock %}

{% block content %}
<form action="{{ url_for('core.create') }}" method="POST" name="order">
  {{ form_order.csrf_token  }}
  <div class="grid-container grid-container-padded">
    <div class="grid-x grid-margin-x">
      <div class="cell small-12 medium-6 large-6">
        <div class="grid-x grid-margin-x" style="margin-top: 10px;">
           {{ error }}
          <div class="cell small-12 medium-6 large-6">
            {{ form_order.ord_num(placeholder="№ Договора") }}
          </div>
          <div class="cell small-12 medium-6 large-6">
          </div>
        </div>
        <div class="cell small-12 medium-12 large-12">
          {{ form_order.client(placeholder="Имя заказчика") }}
        </div>
        <div class="cell small-12 medium-12 large-12">
          {{ form_order.phone(placeholder="Телефон") }}
        </div>
        <hr>
        <div>
          {{ form_order.descr.label("Заметки")}}
          {{ form_order.descr }}
        </div>
      </div>
    </div>
      <input type="submit" class="button" value="Submit">
      <a href="{{ get_ablolute_url }}/core/orders/all">Отмена
    </div>
  </div>
</form>
{% endblock %}